name: 'uks - tfstate storage create'

on:
  workflow_dispatch:
    inputs:
      checks_only:
        description: 'Run in checks-only mode'
        required: true
        type: choice
        options:
        - 'false'
        - 'true'
        default: 'false'

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

jobs:
  create-tfstate-storage:
    uses: elabx-org/alz-reusable-workflows/.github/workflows/terraform-backend-create.yml@main
    with:
      environment: 'uks plan'  # Specify the GitHub environment name
      checks_only: ${{ inputs.checks_only == 'true' }}    
      subnet_ids: '/subscriptions/custom_sub_id/resourceGroups/custom_rg/providers/Microsoft.Network/virtualNetworks/custom_vnet/subnets/custom_subnet1,/subscriptions/custom_sub_id/resourceGroups/custom_rg/providers/Microsoft.Network/virtualNetworks/custom_vnet/subnets/custom_subnet2'
      run_resource_provider_check: true
      run_resource_group_check: true
      run_storage_account_check: true
      run_network_rules_check: false
      run_blob_properties_check: true
      run_container_properties_check: true
      run_backup_checks: true
      create_resource_group: true
      create_storage_account: true
      update_network_rules: false
      create_container: true
      update_blob_policies: true
      update_container_policies: true
      setup_azure_backup: true
    secrets:
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}