name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
    steps:
      - name: Checkout IPAM repo
        uses: actions/checkout@v3
        with:
          repository: azure/ipam
          path: ipam

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Version
        id: version
        run: |
          VERSION="v$(date +'%Y.%m.%d')-${{ github.run_number }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and save Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file ipam/Dockerfile.deb \
            --tag ghcr.io/${{ github.repository_owner }}/ipam:latest \
            --tag ghcr.io/${{ github.repository_owner }}/ipam:${{ env.VERSION }} \
            --output type=docker,dest=/tmp/image.tar \
            ipam

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: /tmp/image.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image
          path: /tmp

      - name: Load Docker image
        run: docker load --input /tmp/image.tar

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/ipam:latest
          docker push ghcr.io/${{ github.repository_owner }}/ipam:${{ needs.build.outputs.version }}
